name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Allow write access to the contents of the repository

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Step 2: Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: therealyash
          svg_out_path: github-contribution-grid-snake.svg
      
      # Step 3: Create the build directory (dist) if it does not exist
      - name: Create dist directory
        run: mkdir -p dist
      
      # Step 4: Copy the generated SVG to the dist directory
      - name: Move Snake Animation to dist
        run: mv github-contribution-grid-snake.svg dist/

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
